[100 numpy exercises - A joint effort of the numpy community](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#100-numpy-exercises" data-toc-modified-id="100-numpy-exercises-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>100 numpy exercises</a></span><ul class="toc-item"><li><span><a href="#1-^-25" data-toc-modified-id="1-^-25-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>1 ^ 25</a></span><ul class="toc-item"><li><span><a href="#Import-the-numpy-package-under-the-name-np-(★☆☆)" data-toc-modified-id="Import-the-numpy-package-under-the-name-np-(★☆☆)-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Import the numpy package under the name np (★☆☆)</a></span></li><li><span><a href="#Print-the-numpy-version-and-the-configuration-(★☆☆)" data-toc-modified-id="Print-the-numpy-version-and-the-configuration-(★☆☆)-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Print the numpy version and the configuration (★☆☆)</a></span></li><li><span><a href="#Create-a-null-vector-of-size-10-(★☆☆)" data-toc-modified-id="Create-a-null-vector-of-size-10-(★☆☆)-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Create a null vector of size 10 (★☆☆)</a></span></li><li><span><a href="#How-to-find-the-memory-size-of-any-array-(★☆☆)" data-toc-modified-id="How-to-find-the-memory-size-of-any-array-(★☆☆)-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>How to find the memory size of any array (★☆☆)</a></span></li><li><span><a href="#How-to-get-the-documentation-of-the-numpy-add-function-from-the-command-line?-(★☆☆)" data-toc-modified-id="How-to-get-the-documentation-of-the-numpy-add-function-from-the-command-line?-(★☆☆)-1.1.5"><span class="toc-item-num">1.1.5&nbsp;&nbsp;</span>How to get the documentation of the numpy add function from the command line? (★☆☆)</a></span></li><li><span><a href="#Create-a-null-vector-of-size-10-but-the-fifth-value-which-is-1-(★☆☆)" data-toc-modified-id="Create-a-null-vector-of-size-10-but-the-fifth-value-which-is-1-(★☆☆)-1.1.6"><span class="toc-item-num">1.1.6&nbsp;&nbsp;</span>Create a null vector of size 10 but the fifth value which is 1 (★☆☆)</a></span></li><li><span><a href="#Create-a-vector-with-values-ranging-from-10-to-49-(★☆☆)" data-toc-modified-id="Create-a-vector-with-values-ranging-from-10-to-49-(★☆☆)-1.1.7"><span class="toc-item-num">1.1.7&nbsp;&nbsp;</span>Create a vector with values ranging from 10 to 49 (★☆☆)</a></span></li><li><span><a href="#Reverse-a-vector-(first-element-becomes-last)-(★☆☆)" data-toc-modified-id="Reverse-a-vector-(first-element-becomes-last)-(★☆☆)-1.1.8"><span class="toc-item-num">1.1.8&nbsp;&nbsp;</span>Reverse a vector (first element becomes last) (★☆☆)</a></span></li><li><span><a href="#Create-a-3x3-matrix-with-values-ranging-from-0-to-8-(★☆☆)" data-toc-modified-id="Create-a-3x3-matrix-with-values-ranging-from-0-to-8-(★☆☆)-1.1.9"><span class="toc-item-num">1.1.9&nbsp;&nbsp;</span>Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)</a></span></li><li><span><a href="#Find-indices-of-non-zero-elements-from-[1,2,0,0,4,0]-(★☆☆)" data-toc-modified-id="Find-indices-of-non-zero-elements-from-[1,2,0,0,4,0]-(★☆☆)-1.1.10"><span class="toc-item-num">1.1.10&nbsp;&nbsp;</span>Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)</a></span></li><li><span><a href="#Create-a-3x3-identity-matrix-(★☆☆)" data-toc-modified-id="Create-a-3x3-identity-matrix-(★☆☆)-1.1.11"><span class="toc-item-num">1.1.11&nbsp;&nbsp;</span>Create a 3x3 identity matrix (★☆☆)</a></span></li><li><span><a href="#Create-a-3x3x3-array-with-random-values-(★☆☆)" data-toc-modified-id="Create-a-3x3x3-array-with-random-values-(★☆☆)-1.1.12"><span class="toc-item-num">1.1.12&nbsp;&nbsp;</span>Create a 3x3x3 array with random values (★☆☆)</a></span></li><li><span><a href="#Create-a-10x10-array-with-random-values-and-find-the-minimum-and-maximum-values-(★☆☆)" data-toc-modified-id="Create-a-10x10-array-with-random-values-and-find-the-minimum-and-maximum-values-(★☆☆)-1.1.13"><span class="toc-item-num">1.1.13&nbsp;&nbsp;</span>Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)</a></span></li><li><span><a href="#Create-a-random-vector-of-size-30-and-find-the-mean-value-(★☆☆)" data-toc-modified-id="Create-a-random-vector-of-size-30-and-find-the-mean-value-(★☆☆)-1.1.14"><span class="toc-item-num">1.1.14&nbsp;&nbsp;</span>Create a random vector of size 30 and find the mean value (★☆☆)</a></span></li><li><span><a href="#Create-a-2d-array-with-1-on-the-border-and-0-inside-(★☆☆)" data-toc-modified-id="Create-a-2d-array-with-1-on-the-border-and-0-inside-(★☆☆)-1.1.15"><span class="toc-item-num">1.1.15&nbsp;&nbsp;</span>Create a 2d array with 1 on the border and 0 inside (★☆☆)</a></span></li><li><span><a href="#How-to-add-a-border-(filled-with-0's)-around-an-existing-array?-(★☆☆)" data-toc-modified-id="How-to-add-a-border-(filled-with-0's)-around-an-existing-array?-(★☆☆)-1.1.16"><span class="toc-item-num">1.1.16&nbsp;&nbsp;</span>How to add a border (filled with 0's) around an existing array? (★☆☆)</a></span></li><li><span><a href="#What-is-the-result-of-the-following-expression?-(★☆☆)" data-toc-modified-id="What-is-the-result-of-the-following-expression?-(★☆☆)-1.1.17"><span class="toc-item-num">1.1.17&nbsp;&nbsp;</span>What is the result of the following expression? (★☆☆)</a></span></li><li><span><a href="#Create-a-5x5-matrix-with-values-1,2,3,4-just-below-the-diagonal-(★☆☆)" data-toc-modified-id="Create-a-5x5-matrix-with-values-1,2,3,4-just-below-the-diagonal-(★☆☆)-1.1.18"><span class="toc-item-num">1.1.18&nbsp;&nbsp;</span>Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)</a></span></li><li><span><a href="#Create-a-8x8-matrix-and-fill-it-with-a-checkerboard-pattern-(★☆☆)" data-toc-modified-id="Create-a-8x8-matrix-and-fill-it-with-a-checkerboard-pattern-(★☆☆)-1.1.19"><span class="toc-item-num">1.1.19&nbsp;&nbsp;</span>Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)</a></span></li><li><span><a href="#Consider-a-(6,7,8)-shape-array,-what-is-the-index-(x,y,z)-of-the-100th-element?" data-toc-modified-id="Consider-a-(6,7,8)-shape-array,-what-is-the-index-(x,y,z)-of-the-100th-element?-1.1.20"><span class="toc-item-num">1.1.20&nbsp;&nbsp;</span>Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?</a></span></li><li><span><a href="#Create-a-checkerboard-8x8-matrix-using-the-tile-function-(★☆☆)" data-toc-modified-id="Create-a-checkerboard-8x8-matrix-using-the-tile-function-(★☆☆)-1.1.21"><span class="toc-item-num">1.1.21&nbsp;&nbsp;</span>Create a checkerboard 8x8 matrix using the tile function (★☆☆)</a></span></li><li><span><a href="#Normalize-a-5x5-random-matrix-(★☆☆)" data-toc-modified-id="Normalize-a-5x5-random-matrix-(★☆☆)-1.1.22"><span class="toc-item-num">1.1.22&nbsp;&nbsp;</span>Normalize a 5x5 random matrix (★☆☆)</a></span></li><li><span><a href="#Create-a-custom-dtype-that-describes-a-color-as-four-unsigned-bytes-(RGBA)-(★☆☆)" data-toc-modified-id="Create-a-custom-dtype-that-describes-a-color-as-four-unsigned-bytes-(RGBA)-(★☆☆)-1.1.23"><span class="toc-item-num">1.1.23&nbsp;&nbsp;</span>Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)</a></span></li><li><span><a href="#Multiply-a-5x3-matrix-by-a-3x2-matrix-(real-matrix-product)-(★☆☆)" data-toc-modified-id="Multiply-a-5x3-matrix-by-a-3x2-matrix-(real-matrix-product)-(★☆☆)-1.1.24"><span class="toc-item-num">1.1.24&nbsp;&nbsp;</span>Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)</a></span></li><li><span><a href="#Given-a-1D-array,-negate-all-elements-which-are-between-3-and-8,-in-place.-(★☆☆)" data-toc-modified-id="Given-a-1D-array,-negate-all-elements-which-are-between-3-and-8,-in-place.-(★☆☆)-1.1.25"><span class="toc-item-num">1.1.25&nbsp;&nbsp;</span>Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)</a></span></li></ul></li></ul></li></ul></div>

100 numpy exercises
===

1 ^ 25
---

### Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

### Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.16.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


### Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### How to find the memory size of any array (★☆☆)

In [4]:
print('size: ', Z.size)
print('itemsize: ', Z.itemsize)

size:  10
itemsize:  8


### How to get the documentation of the numpy add function from the command line? (★☆☆)

```bash
$ python3 -c "import numpy; numpy.info(numpy.add)"
```

In [5]:
# from program
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
# numpy.arrange(start, end)
# end は含まない
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Reverse a vector (first element becomes last) (★☆☆)

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)
# 一応、こっちでも。
# print(np.array([[0,1,2],[3,4,5],[6,7,8]]))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


### Create a 3x3 identity matrix (★☆☆)

In [11]:
# 単位行列
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Create a 3x3x3 array with random values (★☆☆)

In [12]:
Z = np.random.random([3,3,3])
print(Z)

[[[0.10301572 0.31987317 0.29229821]
  [0.91690489 0.11891109 0.85130169]
  [0.83602769 0.59379181 0.05457459]]

 [[0.93033446 0.35760525 0.8095513 ]
  [0.8695436  0.51158606 0.48328218]
  [0.95849285 0.27475055 0.40002692]]

 [[0.93040382 0.4266408  0.41672793]
  [0.85573423 0.66318208 0.77688488]
  [0.09421105 0.84499046 0.33472632]]]


### Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
Z = np.random.random((10,10))
print('min: ', Z.min())
print('max: ', Z.max())

min:  0.005462351025345202
max:  0.9994228939462118


### Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
Z = np.random.random(30)
print('mean: ', Z.mean())

mean:  0.5395054645537942


### Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant')
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### What is the result of the following expression? (★☆☆)

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


### Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
Z = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Normalize a 5x5 random matrix (★☆☆)

In [22]:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[-1.5071509   1.73150117 -0.07556024 -1.19852788 -0.10117527]
 [-1.33335758  1.20519981  1.54224883  0.92347661  1.00430238]
 [-1.59851024  0.5953577   0.51917663  1.66923927  0.1735156 ]
 [-0.39749085 -1.13380403  0.09559887 -0.20962277  0.7436047 ]
 [-1.31719681 -0.59605608 -0.56269969 -0.49877553  0.32670631]]


### Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([('r', np.ubyte, 1),
                 ('g', np.ubyte, 1),
                 ('b', np.ubyte, 1),
                 ('a', np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


### Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)



[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
